"use client";

import { useState } from "react";

// export const metadata = {
// 	title: {
// 		default: "NextJs is like Meth",
// 		template: "%s | Amigoss",
// 	},
// 	description: "Generated by Next.js",
// };

export default function MarketingLayout({ children }: { children: React.ReactNode }) {
	const [input, setInput] = useState("");
	return (
		<html lang="en">
			<body>
				<header
					style={{
						backgroundColor: "peachpuff",
						display: "grid",
						placeContent: "center",
						padding: "1rem",
					}}
				>
					Header
				</header>
				<input value={input} onChange={(e) => setInput(e.target.value)} />
				{children}

				<footer
					style={{
						backgroundColor: "whitesmoke",
						display: "grid",
						placeContent: "center",
						padding: "1rem",
					}}
				>
					Footer
				</footer>
			</body>
		</html>
	);
}
