"use client";
import Link from "next/link";
import { usePathname } from "next/navigation";

// export const metadata = {
// 	title: "Next.js",
// 	description: "Generated by Next.js",
// };
const navLinks = [
	{ name: "Register", path: "/Customer/register" },
	{ name: "Login", path: "/Customer/login" },
	{ name: "Forgot Password", path: "/Customer/forgot-password" },
];
export default function AuthLayout({ children }: { children: React.ReactNode }) {
	const pathname = usePathname();

	return (
		<html lang="en">
			<body>
				{navLinks.map((link) => (
					<Link href={link.path} key={link.name}>
						{link.name}
					</Link>
				))}
				{children}

				<footer
					style={{ backgroundColor: "whitesmoke", display: "grid", placeContent: "center", padding: "1rem" }}
				>
					Footer
				</footer>
			</body>
		</html>
	);
}

//NOTE : You can use isActive
